import type { Metadata } from "next";

export const links = {
  sourceCode: "",
  ownerName: "Ansh Thakare",
  ownerEmail: "thakareansh3@gmail.com",
  linkedin: "https://www.linkedin.com/in/ansh-thakare-053783359",
  instagram: "https://www.instagram.com/ash.thakare_22",
  whatsapp: "https://wa.me/919226139414",
  resume: "/ansh/Ansh_Thakare_Resume.pdf",
} as const;

export const siteConfig: Metadata = {
  title: "Ansh Thakare | AI & Data Science",
  description: "Aspiring AI and Data Science professional with a passion for building innovative solutions and a proven track record of discipline from competitive sports.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "aceternity",
    "aceternity-ui",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "modern-portfolio",
    "portfolio",
    "3d-portfolio",
    "animated-portfolio",
    "nextjs-portfolio",
    "react-portfolio",
    "react-three-fiber",
    "three.js",
    "animated-website",
    "framer",
    "framer-motion",
    "three",
    "react-icons",
    "lucide-react",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: links.ownerName,
    url: "",
  },
} as const;
